plot_pd('random','ippg')
plot_pd('sulci cutis','ippg')
plot_pd('sinus','ippg')
plot_pd('normal','ippg')
plot_pd('random','ppg')
plot_pd('sulci cutis','ppg')
plot_pd('sinus','ppg')
plot_pd('normal','ppg')


plot_sensor('random','ippg')
plot_sensor('sulci cutis','ippg')
plot_sensor('sinus','ippg')
plot_sensor('normal','ippg')
plot_sensor('random','ppg')
plot_sensor('sulci cutis','ppg')
plot_sensor('sinus','ppg')
plot_sensor('normal','ppg')